from selenium import webdriver
from selenium.webdriver.support.select import Select
driver = webdriver.Chrome("C:\Program Files (x86)\chromedriver_win32\chromedriver.exe")
driver.fullscreen_window()
driver.get('http://automationpractice.com/index.php')
driver.find_element_by_xpath("//a[@title='Log in to your customer account']").click()
driver.find_element_by_xpath("//input[@name='email_create']").send_keys("zqwaterloo@gmail.com\n")
driver.find_element_by_xpath("//button[@id='SubmitCreate']//span[1]").click()
driver.implicitly_wait(5)
driver.find_element_by_xpath("//*[@id='uniform-id_gender1']").click()
driver.find_element_by_xpath("//input[@id='customer_firstname']").send_keys("Qing")
driver.find_element_by_xpath("//input[@id='customer_lastname']").send_keys("Zhang")
driver.find_element_by_xpath("//input[@id='passwd']").send_keys("zhangqing123")
dayselements=driver.find_element_by_id("days")
days=Select(dayselements)
days.select_by_value("1")
monthselements=driver.find_element_by_id("months")
months=Select(monthselements)
months.select_by_value("10")
yearselements=driver.find_element_by_id("years")
years=Select(yearselements)
years.select_by_value("1989")
driver.find_element_by_xpath("//input[@name='firstname']").send_keys("Qing")
driver.find_element_by_xpath("//input[@id='lastname']").send_keys("Zhang")

driver.find_element_by_xpath("//input[@id='address1']").send_keys("385 erb street")
driver.find_element_by_xpath("//input[@id='city']").send_keys("waterloo")
stateselements=driver.find_element_by_id("id_state")
states=Select(stateselements)
states.select_by_value("50")
driver.find_element_by_xpath("//input[@id='postcode']").send_keys("82054")
driver.find_element_by_xpath("//input[@id='phone_mobile']").send_keys("2268996384")
driver.find_element_by_xpath("//input[@id='alias']").send_keys("375 erb street")
driver.find_element_by_xpath("//span[contains(text(),'Register')]").click()
driver.quit()
